Space application supporter can access environment variable groups
cloudfoundry/cloud_controller_ng pull request #2325
Opened 2021-06-10 10:26 UTC by will-gant

* Add unit tests to prove that all roles can _get_ access environment variable groups and that only the admin role can _update_ environment variable groups (as documented [here](https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#get-an-environment-variable-group) and [here](https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#update-environment-variable-group))

Closes #2221

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `main` branch

* [x] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

2021-06-11 19:52 UTC, sweinstein22 commented
## Acceptance

### Setup

Created environment variables for `staging` and `running` groups as `admin`:
```
$ cf curl -X PATCH /v3/environment_variable_groups/staging -d '{"var":{"test_staging":"variable_staging"}}'
$ cf curl -X PATCH /v3/environment_variable_groups/running -d '{"var":{"test_running":"variable_running"}}'
```

Confirmed that `admin` could view both groups
```
$ cf curl /v3/environment_variable_groups/staging
{
  "name": "staging",
  "var": {
    "test_staging": "variable_staging"
  },
  ...
}

$ cf curl /v3/environment_variable_groups/running
{
  "name": "running",
  "var": {
    "test": "variable"
  },
  ...
}
```

Confirmed user only has space_application_supporter and organization_user roles:

```
$ cf curl /v3/roles?user_guids="0776980f-9ea5-499a-9a23-ecc09d0d5b39"
{
  ...
  "resources": [
    {
      "guid": "7555955f-5baf-4700-93e1-3952ef664a1f",
      "type": "organization_user",
      "relationships": {
        "user": {
          "data": {
            "guid": "0776980f-9ea5-499a-9a23-ecc09d0d5b39"
          }
        },
      ...
    },
    {
      "guid": "e158488c-2b95-4806-a6f1-68df9dde8fdc",
      "type": "space_application_supporter",
      "relationships": {
        "user": {
          "data": {
            "guid": "0776980f-9ea5-499a-9a23-ecc09d0d5b39"
          }
        },
       ...
  ]
}
```

### Behavior Check

Ran `cf curl` against `/v3/environment_variable_groups/running`, `/v3/environment_variable_groups/staging`, and `/v3/environment_variable_groups/bogus` as both space application supporter and space developer, confirmed that there was no diff and manually confirmed that output looked correct:
```
$ diff space-app-supporter-running space-dev-running

$ diff space-app-supporter-staging space-dev-running

$ diff space-app-supporter-bogus space-dev-bogus

```

Confirmed that space application supporter does not have permission to hit `PATCH` endpoint:
```
$ cf curl -X PATCH /v3/environment_variable_groups/staging -d '{"var":{"test_staging":"variable_staging"}}'
{
  "errors": [
    {
      "detail": "You are not authorized to perform the requested action",
      "title": "CF-NotAuthorized",
      "code": 10003
    }
  ]
}
```

### Code Review

This change did not require any changes to the implementation. Some adjustments to the request spec changes would bring the spec more inline with the current patterns of the file.

### Docs

No changes required, as the docs already indicate that this endpoint is available to all roles.

2021-06-11 19:53 UTC, sweinstein22 requested changes
### Requested changes to `environment_variable_groups_spec.rb`

#### `describe 'GET /v3/environment_variable_groups/:name'`

Minor detail but it would be more inline with [current patterns of the file](https://github.com/cloudfoundry/cloud_controller_ng/blob/72f7115f3fcea74625c414527b287a4668e11755/spec/request/environment_variable_groups_spec.rb#L172) to call the new context 'when the user is logged in'

#### `describe 'PATCH /v3/environment_variable_groups/:name'`

The added changes to the spec are on the right track, but the organization of the tests is a bit disjointed with these changes. There's a [section that was already doing the shared examples testing for `staging`](https://github.com/cloudfoundry/cloud_controller_ng/blob/72f7115f3fcea74625c414527b287a4668e11755/spec/request/environment_variable_groups_spec.rb#L200), which haven't been updated to include the new role. There's also [a section dedicated to the `running` group](https://github.com/cloudfoundry/cloud_controller_ng/blob/72f7115f3fcea74625c414527b287a4668e11755/spec/request/environment_variable_groups_spec.rb#L101-L123), which the newly introduced permissions check is not part of.

As the pattern in this describe block is to do the majority of the tests for just one of the two cases (`running` or `staging`) because they run through the same controller flow, it would be great to adjust the tests so that we update the existing permission test under the `staging` context, and scrap the one testing against `running`.

2021-06-14 12:30 UTC, will-gant commented
Many thanks for the thorough review and apologies for the sloppiness on my side. I think/hope I've now implemented each of the improvements you've suggested.

2021-06-14 16:21 UTC, sweinstein22 commented
No worries, thanks for making the adjustments, looks good!

2021-06-14 16:21 UTC, merged