Space application supporter can list service offerings
cloudfoundry/cloud_controller_ng pull request #2364
Opened 2021-07-05 09:30 UTC by will-gant

* Enable space application supporter to list service offerings
* Add tests to prove the above

Closes #2240 

This PR [assumes](https://github.com/cloudfoundry/cloud_controller_ng/issues/2240#issuecomment-873949705) that, although the endpoint is not mentioned in the user story, the space application supporter is in fact supposed to have limited access to the `/v3/service_offerings/:guid` (on a par with that available to space auditors). If this is a faulty assumption, more changes will be needed.

It was necessary to duplicate changes to [lib/cloud_controller/permissions.rb](https://github.com/sap-contributions/cloud_controller_ng/commit/ea603b10ef491f32f257cd3ab996b432e258f2a8#diff-a291f406c35429c28a43b02ce43619b89c8476c7fe94cc7089a1f75432acd03bR218) and [lib/cloud_controller/permissions/queryer.rb](https://github.com/sap-contributions/cloud_controller_ng/commit/ea603b10ef491f32f257cd3ab996b432e258f2a8#diff-1892e2cb4b2958f0084895dc85b342c1d8aa436cb1abf5a0bd864de8be64e79eR132) that have already been made in the open PR #2349 for service plans. Once both PRs are accepted I think it will be necessary to go back and remove the functions readable_space_scoped_space_guids in both files, as those will no longer be in use.

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `main` branch

* [x] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

2021-07-12 11:14 UTC, will-gant commented
I've just amended my original commit to give the role the new name

2021-07-13 22:46 UTC, monamohebbi commented
As per the conversation in the associated issue, please also allow the space supporter access to `/v3/service_offerings/:guid` as a part of this PR. Thanks!

2021-07-14 15:55 UTC, will-gant commented
@monamohebbi Thanks for the feedback. The space supporter can now get `/v3/service_offerings/:guid`, and gets a 403 when it tries to do a patch or delete. Let me know what you think.

2021-07-15 20:42 UTC, monamohebbi commented
Hello! Just given the unfortunate messy rebase around the pr for [service_plans](https://github.com/cloudfoundry/cloud_controller_ng/pull/2349), could you try rebasing again post refactoring before we run acceptance testing? Sorry about that (ps have a nice vacation!).

2021-07-15 20:44 UTC, monamohebbi requested changes
Hello! Just given the unfortunate messy rebase around the pr for service_plans, could you try rebasing again post refactoring before we run acceptance testing? Sorry about that (ps have a nice vacation!).

2021-07-20 08:44 UTC, iaftab-alam commented
hey @monamohebbi we have done the rebase and resolved the conflicts.

Regards,
Aftab

2021-07-22 22:54 UTC, monamohebbi approved these changes
## Acceptance

### Behavior Check

Setup: created 4 service offerings each assigned a plan with a different visibility type from set admin, org, space, and public. 

#### `GET` Endpoints
Ran `cf curl` against `/v3/service_offerings/:guid`, `/v3/service_offerings` as a space supporter in the targeted org and space. Manually confirmed output looked correct, and checked for diffs:
```
$ diff dev supporter

$ diff show_dev show_supporter

```

#### `GET` Endpoints when assigned a role in a separate space in the same org
Confirmed that output looked correct manually. Checked that diff only included timestamps, guids, and user details under `created_by` section:
```
$ diff otherspace_dev otherspace_supporter

$ diff otherspace_show_dev otherspace_show_supporter

```

#### `GET` Endpoints when assigned a role in a separate org
Confirmed that output looked correct manually. Checked that diff only included timestamps, guids, and user details under `created_by` section:
```
$ diff otherorg_dev otherorg_supporter

$ diff otherorg_show_dev otherorg_show_supporter

```

#### DELETE and PATCH 403s
Running `cf curl -X PATCH v3/service_offerings/:guid` as a space supporter to an org that is unaffiliated with the specified service plan returns:
```
{
   "errors": [
      {
         "detail": "You are not authorized to perform the requested action",
         "title": "CF-NotAuthorized",
         "code": 10003
      }
   ]
}
```
Running `cf curl -X DELETE v3/service_offerings/:guid` as a space supporter to an org that is unaffiliated with the specified service plan returns:
```
{
   "errors": [
      {
         "detail": "You are not authorized to perform the requested action",
         "title": "CF-NotAuthorized",
         "code": 10003
      }
   ]
}
```
LGTM!

2021-07-22 23:01 UTC, sweinstein22 approved these changes
### Code Check

Looks good, leverages request spec shared examples and established helper functions in implementation

### Docs Check

Confirmed that both GET endpoints already indicate that they're available to all roles, and that space supporter is not listed for the PATCH and DELETE endpoints; no changes required

Thanks for the PR!

2021-07-22 23:01 UTC, merged