Space application supporter can get, list service instances
cloudfoundry/cloud_controller_ng pull request #2378
Opened 2021-07-07 14:54 UTC by will-gant

* Space application supporter can get and list service instances, and list shared spaces relationships of service instances.
* Unit tests to prove the above.

Closes #2238 

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `main` branch

* [x] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

2021-07-15 16:44 UTC, sweinstein22 commented
Hi @will-gant , it looks like we picked up a few merge conflicts when merging in the [PR removing residual perm code](https://github.com/cloudfoundry/cloud_controller_ng/pull/2405). Apologies for any inconvenience this may have caused.

If we get around to looking at this PR today we will try to help resolve them, thanks again for taking the time to make contributions to the codebase!

2021-07-20 08:59 UTC, iaftab-alam commented
Hey @sweinstein22,

The conflicts are resolved.

Regards,
Aftab

2021-07-20 17:44 UTC, sweinstein22 reviewed
## Acceptance

### Behavior Check

Ran `cf curl` against `/v3/service_instances`, `/v3/service_instances/:guid`, `/v3/service_instaces/:guid/relationships/shared_spaces` as both a space supporter and a space developer, confirmed output looked correct manually and checked for a diff:
```
$ diff space-supporter-service-instances space-dev-service-instances

$ diff space-supporter-service-instances-guid space-dev-service-instances-guid

$ diff space-supporter-service-instances-guid-spaces space-dev-service-instances-guid-spaces

```

### Code Check

Changes look good, leverages the patterns set up for this work

2021-07-20 17:44 UTC, sweinstein22 requested changes
### Docs Check

Minor detail, if we could alphabetize the roles (by putting Space Supporter at the end of the list) that would be great, otherwise this PR looks good to go, thanks!

2021-07-21 08:30 UTC, iaftab-alam commented
hey @sweinstein22,

Thank you for your feedback. Changes are done. 
Regards,
Aftab

2021-07-21 18:30 UTC, sweinstein22 approved these changes
Great, thanks @iaftab-alam ! We're working out an issue in our pipelines at the moment, I'll merge this in once it's resolved.

2021-07-22 18:27 UTC, merged