Allow user to filter routes by service instance guid
cloudfoundry/cloud_controller_ng pull request #2440
Opened 2021-07-23 22:55 UTC by moleske

closes #2433

Authored-by: Michael Oleske <moleske@pivotal.io>

Things you should check
- make sure I followed the right rubyisms (still getting used to ruby)
- that database query looks efficient to you (seemed alright)
- the implementation in route_fetcher has the extra function because rubocop was giving me failure about "cyclomatic complexity".  I don't really like the solution I wrote, but it made rubocop happy
- docs look right

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `main` branch

* [x] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

2021-07-23 23:45 UTC, sweinstein22 reviewed
### Behavior Check

Currently it looks like we're returning routes that are associated with apps associated with the provided list of service instances. The behavior I was looking for is actually app-agnostic, so returning any routes associated with a service instance, regardless of the apps that route is bound to

For context, service route bindings are not dependent on apps, so the relationship between services and routes can be completely separate from the relationship between apps and routes

Behavior check that I'd like to run successfully looks like the following:

```
$ cf curl /v3/service_route_bindings
...
   {
      "guid": "f518f1d1-08e2-4a62-9434-9cb6955c7b45",
      "route_service_url": "https://logging-route-service.bosh-lite.com",
      "relationships": {
        "service_instance": {
          "data": {
            "guid": "c8754c1c-b0ec-42ba-97b2-e4cec9b367ab"
          }
        },
        "route": {
          "data": {
            "guid": "4043dff2-638b-4591-9363-dc1e05d05e31"
          }
        }
      },
      ...
    }
...

$ cf curl /v3/routes?service_instance_guids=c8754c1c-b0ec-42ba-97b2-e4cec9b367ab
// Returns a paginated response containing at least one element matching route guid 4043dff2-638b-4591-9363-dc1e05d05e31
```

Hopefully that makes sense, if not let me know!

2021-07-26 23:41 UTC, weymanf commented
We made it so it will be app agnostic and search for all routes bounded to searched service instances. @sweinstein22

2021-07-27 16:45 UTC, sweinstein22 requested changes
## Acceptance

Confirmed that associated route appears in filtered result:

```
$ cf curl /v3/service_route_bindings
{
  "pagination": {
    "total_results": 2,
    "total_pages": 1,
    ...
  "resources": [
    ...
    {
      "guid": "f518f1d1-08e2-4a62-9434-9cb6955c7b45",
      "route_service_url": "https://logging-route-service.bosh-lite.com",
      ...
      "relationships": {
        "service_instance": {
          "data": {
            "guid": "c8754c1c-b0ec-42ba-97b2-e4cec9b367ab"
          }
        },
        "route": {
          "data": {
            "guid": "4043dff2-638b-4591-9363-dc1e05d05e31"
          }
        }
      }
    }
  ]
}

$ cf curl /v3/routes?service_instance_guids=c8754c1c-b0ec-42ba-97b2-e4cec9b367ab
{
  "pagination": {
    "total_results": 2,
    "total_pages": 1,
    "first": {
      "href": "https://api.clover-horse.capi.land/v3/routes?page=1&per_page=50&service_instance_guids=c8754c1c-b0ec-42ba-97b2-e4cec9b367ab"
    },
    "last": {
      "href": "https://api.clover-horse.capi.land/v3/routes?page=1&per_page=50&service_instance_guids=c8754c1c-b0ec-42ba-97b2-e4cec9b367ab"
    },
    "next": null,
    "previous": null
  },
  "resources": [
    {
      "guid": "2ac223e7-1c09-4d2d-a612-8c9d4ffcc5cd",
      ...
    },
    {
      "guid": "4043dff2-638b-4591-9363-dc1e05d05e31",
     ...
  ]
}

```

Seems like the route doesn't show if filtering by both service instance and app.

Confirmed that route with guid `4043dff2-638b-4591-9363-dc1e05d05e31` is also tied to app:
```
cf curl /v3/routes?app_guids=0e58e321-4d06-4251-a4fb-8379b42e829b
{
  "pagination": {
    "total_results": 2,
    "total_pages": 1,
    "first": {
      "href": "https://api.clover-horse.capi.land/v3/routes?app_guids=0e58e321-4d06-4251-a4fb-8379b42e829b&page=1&per_page=50"
    },
    "last": {
      "href": "https://api.clover-horse.capi.land/v3/routes?app_guids=0e58e321-4d06-4251-a4fb-8379b42e829b&page=1&per_page=50"
    },
    "next": null,
    "previous": null
  },
  "resources": [
    ...
    {
      "guid": "4043dff2-638b-4591-9363-dc1e05d05e31",
      "destinations": [
        {
          "guid": "10560239-9bc6-4737-813f-5bbb6bbc7c3c",
          "app": {
            "guid": "0e58e321-4d06-4251-a4fb-8379b42e829b",
            "process": {
              "type": "web"
            }
          },
          "weight": null,
          "port": 8080
        }
      ],
      ...
  ]
}
```

Combined the two filters:

```
$ cf curl "/v3/routes?service_instance_guids=c8754c1c-b0ec-42ba-97b2-e4cec9b367ab&app_guids=0e58e321-4d06-4251-a4fb-8379b42e829b"
{
  "pagination": {
    "total_results": 0,
    "total_pages": 1,
    "first": {
      "href": "https://api.clover-horse.capi.land/v3/routes?app_guids=0e58e321-4d06-4251-a4fb-8379b42e829b&page=1&per_page=50&service_instance_guids=c8754c1c-b0ec-42ba-97b2-e4cec9b367ab"
    },
    "last": {
      "href": "https://api.clover-horse.capi.land/v3/routes?app_guids=0e58e321-4d06-4251-a4fb-8379b42e829b&page=1&per_page=50&service_instance_guids=c8754c1c-b0ec-42ba-97b2-e4cec9b367ab"
    },
    "next": null,
    "previous": null
  },
  "resources": [

  ]
}
```

Let me know if it seems like I've misstepped somewhere in checking the behavior on this one

2021-07-27 17:18 UTC, sweinstein22 commented
I think I see it actually, looks like we're doing some fun logic where:
- If an app guid is provided alone, we find all routes mapped to that app
- If a service instance guid is provided alone, we find all routes mapped to that service instance
- If a service instance guid and an app guid are provided, we find all routes mapped to both where the app is also bound to the service instance

I think it makes more sense to ignore the app <=> service instance connection, since the resource in question is routes, but feel free to push back if y'all think otherwise

2021-07-27 18:36 UTC, mariash commented
@sweinstein22 That makes total sense. It will match existing functionality where filters are applied on top of each other. WE updated the PR.

2021-07-27 18:55 UTC, sweinstein22 approved these changes
## Acceptance

Confirmed that service instance filter alone still works:

```
$ cf curl '/v3/routes?service_instance_guids=c8754c1c-b0ec-42ba-97b2-e4cec9b367ab'
{
  "resources": [
    ...
    {
      "guid": "4043dff2-638b-4591-9363-dc1e05d05e31",
      ...
    }
  ]
}
```

Confirmed that service instance and app guid filters combined work:

```
cf curl "/v3/routes?service_instance_guids=c8754c1c-b0ec-42ba-97b2-e4cec9b367ab&app_guids=0e58e321-4d06-4251-a4fb-8379b42e829b"
{
  ...
  "resources": [
    {
      "guid": "4043dff2-638b-4591-9363-dc1e05d05e31",
      ...
    }
  ]
}
```

Code looks good and docs changes have been made. Thanks for the PR!

2021-07-27 19:30 UTC, merged