Adds delete shared routes endpoint
cloudfoundry/cloud_controller_ng pull request #2810
Opened 2022-05-19 22:50 UTC by klakin-pivotal

NOTE: This PR depends on PR #2803. It would be a bad idea to merge this before that. I have marked it as a Draft PR to maybe help prevent it from getting accidentally merged.

This PR adds the endpoint required to delete any routes shared by the endpoint in PR #2803, as well as the tests and documentation related to this delete endpoint. 

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `main` branch

* [x] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

2022-05-20 21:19 UTC, MerricdeLauney requested changes

2022-05-20 22:02 UTC, klakin-pivotal commented on app/actions/route_share.rb
> +    def delete(route, target_space, user_audit_info)
Sure. I'll try to get that done by end of day.

2022-05-20 22:25 UTC, klakin-pivotal commented on app/actions/route_share.rb
> +    def delete(route, target_space, user_audit_info)
K, I think I correctly made the refactor. I haven't run _all_ the tests, but I believe I did run all the relevant tests, which all succeeded.

2022-05-20 22:28 UTC, klakin-pivotal commented on app/controllers/v3/routes_controller.rb
> +
@MerricdeLauney So, this reads a little weirdly: "`unshare.delete`", but I couldn't come up with a better set of names after a few minutes of thinking. Alternatives are very welcome.

2022-05-23 23:53 UTC, MerricdeLauney approved these changes

2022-05-23 23:55 UTC, merged