Stream CCDB migration logs to ELK
cloudfoundry/cloud_controller_ng pull request #3672
Opened 2024-03-04 12:36 UTC by WeiQuan0605

Thanks for contributing to cloud_controller_ng. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:

* An explanation of the use cases your change solves

* Links to any other associated PRs

* [X] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [X] I have viewed, signed, and submitted the Contributor License Agreement

* [X] I have made this pull request to the `main` branch

* [X] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/spec/README.md#cf-acceptance-tests-cats)

2024-03-07 14:56 UTC, johha approved these changes
LGTM

2024-03-08 14:03 UTC, philippthun commented on lib/cloud_controller/db.rb
> +  def logger
This is not used in the test migration.

Ideally one could use `log_info` from the `Sequel::Database` class in a migration ([here](https://github.com/jeremyevans/sequel/blob/70bcc08e47b060957e37584ee85c304d5698ef7c/lib/sequel/database/logging.rb#L31)).

2024-04-04 10:10 UTC, johha approved these changes
LGTM

2024-04-04 11:36 UTC, philippthun requested changes

2024-04-04 11:36 UTC, philippthun commented on lib/tasks/db.rake
> +  def logging_output
The task `ensure_migrations_are_current` also calls `Steno.init`. This can be replaced with `logging_output` as well.

2024-04-04 11:36 UTC, philippthun commented on spec/migrations/migration_logs_to_elk_spec.rb
> +require 'spec_helper'
`_to_elk` is not tested here, thus I would rename the file to `migration_logs_spec.rb` as it tests logs written during a migration.

2024-04-04 11:36 UTC, philippthun commented on spec/migrations/migration_logs_to_elk_spec.rb
> +RSpec.describe 'migration ccdb logs to elk', isolation: :truncation, type: :migration do
```suggestion
RSpec.describe 'migration logs', isolation: :truncation, type: :migration do
```

2024-04-04 11:36 UTC, philippthun commented on spec/migrations/migration_logs_to_elk_spec.rb
> +            VCAP::Migration.logging('Still Migrating')
When changing the method in `VCAP::Migration` as described above, this should be:
```
VCAP::Migration.logger.info(...)
```

2024-04-04 11:36 UTC, philippthun commented on spec/migrations/migration_logs_to_elk_spec.rb
> +    Sequel::Migrator.run(db, tmp_migrations_dir, allow_missing_migration_files: true)
I think the `after` block should revert the migration, i.e. add param `target: 0`.

2024-04-04 11:36 UTC, philippthun commented on spec/migrations/migration_logs_to_elk_spec.rb
> +    expect { Sequel::Migrator.run(db, tmp_migrations_dir, target: 0, allow_missing_migration_files: true) }.not_to raise_error
Here the `target: 0` param is wrong as we want to run the migration, not revert it.

2024-04-04 11:36 UTC, philippthun commented on spec/migrations/migration_logs_to_elk_spec.rb
> +    allow(VCAP::Migration).to receive(:logging)
To test the changed method in `VCAP::Migration` I suggest the following:

1. Define a `logger` test variable: `let(:logger) { instance_double(Steno::Logger) }`
2. Allow `Steno.logger` to be called only with the correct name (and return the mock from above): `allow(Steno).to receive(:logger).with('cc.db.migrations').and_return(logger)`
3. Expect that the correct messages are sent to `logger.info`: `expect(logger).to receive(:info).with(...)`

2024-04-04 12:56 UTC, philippthun approved these changes

2024-04-11 08:21 UTC, merged