Add dynamic job priorities
cloudfoundry/cloud_controller_ng pull request #3703
Opened 2024-03-27 10:31 UTC by svkrieger

Thanks for contributing to cloud_controller_ng. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:

* An explanation of the use cases your change solves

* Links to any other associated PRs

* [ ] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [ ] I have viewed, signed, and submitted the Contributor License Agreement

* [ ] I have made this pull request to the `main` branch

* [ ] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/spec/README.md#cf-acceptance-tests-cats)

2024-04-15 12:53 UTC, johha requested changes

2024-04-16 05:57 UTC, svkrieger commented on spec/unit/jobs/enqueuer_spec.rb
> +require_relative '../../../lib/cloud_controller/user_audit_info'
Oh that's indeed just a leftover. After inclusing `spec_helper` this is not needed anymore.

2024-04-16 05:58 UTC, svkrieger commented on spec/unit/jobs/enqueuer_spec.rb
>        end
Good catch! I added this test case.

2024-04-16 06:14 UTC, svkrieger commented on db/migrations/20240314131908_add_user_guid_to_jobs_table.rb
> +        add_column :user_guid, String, size: 255, if_not_exists: true
Both are used. Seems like there is no performance difference between the two (https://www.postgresql.org/docs/current/datatype-character.html). I don't have a strong opinion here.

2024-04-18 13:39 UTC, johha approved these changes

2024-04-18 13:58 UTC, merged