Prevent 500 on parallel object creation
cloudfoundry/cloud_controller_ng pull request #3918
Opened 2024-08-02 11:45 UTC by kathap

While fixing #3899, we found further possible occurrences of 500 errors in severel _create actions when doing parallel requests. In this PR we want to address them by adding an around_save to the corresponding model in which we catch Sequel::UniqueConstraintViolation errors for the case when  ne POST bypasses the other one and inserts the record into the db after the first POST has passed the validate function but before the actual insert.

* A short explanation of the proposed change:
Adding an around_save to the corresponding model in which we catch Sequel::UniqueConstraintViolation errors for the case when  ne POST bypasses the other one and inserts the record into the db after the first POST has passed the validate function but before the actual insert
* An explanation of the use cases your change solves
No more 500 errors on parallel request execution

* Links to any other associated PRs
#3899
* [X] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `main` branch

* [X] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/spec/README.md#cf-acceptance-tests-cats)

2024-08-14 09:12 UTC, svkrieger reviewed
Looks great! Just a question about mocking in two tests and a minor finding.

EDIT: Also do we plan to get rid of the unique checks in the coding? If we catch the unique constraint errors thrown by the DB reliably now, it should not be necessary to check for uniqueness beforehand.

2024-08-14 09:12 UTC, svkrieger commented on spec/unit/actions/service_credential_binding_app_create_spec.rb
> +              allow_any_instance_of(ServiceBinding).to receive(:save_with_attributes_and_new_operation) do |instance|
Same question here

2024-08-14 09:12 UTC, svkrieger commented on spec/unit/isolation_segment_create_spec.rb
> +          end.to raise_error(IsolationSegmentCreate::Error)
Would be good to test for the error string here, like done in all other tests.

2024-08-14 15:14 UTC, kathap commented on spec/unit/actions/service_credential_binding_app_create_spec.rb
> +              allow_any_instance_of(ServiceBinding).to receive(:save_with_attributes_and_new_operation) do |instance|
Good point!

2024-08-19 09:03 UTC, svkrieger requested changes

2024-08-19 09:03 UTC, svkrieger commented on spec/unit/actions/service_credential_binding_key_create_spec.rb
> +          let(:service_instance2) { ManagedServiceInstance.make(space:) }
We don't need a second service instance, name and message here. The constraint is on the name of the keys per service instance.

2024-08-19 12:06 UTC, svkrieger approved these changes

2024-08-22 12:27 UTC, merged